version: v1                                          # @v5.0
kind: simloud-pipeline

pipeline:
  default:                                          # profile name. Currently, only default
    - hook: process                                 # by default, it is process.  There are preprocess,postprocess values are available
      state: build                                  # by default, it is build value. It is possible to  choose “build,update,create,destroy”
      action: deploy                                # by default, it is deploy value.  It is possible to choose “deploy,destroy”

      stages:
        # === Terraform ===
        - name: “TF code”
          shell: terraform                            # for terraform case
          homedir: ./                                 # shell command directory
          terraform:
            version: 0.12                             # tf version, by default 0.12
            workspace: `name_of_workspace`;           # Workspace’s name. Default workspace: default
            statefile:                                # state file location
              storage: kubernetes                     # by default it is “kubernetes” (k8s). There are consul|file|s3 values are available
              location: /terraform/uuid/              # k8s: <namespace>.<secret_suffix>
            secrets:                                  # `-var-file="testing.tfvars"`
              - storage: (vault|kubernetes)           # vault or k8s secrets
                paths:                                # vault pats, or k8s secrets names
                  - /secrets/<srn:deployment>/sqs     # vault full location path
                  - /ssh/<srn:deployment>/ssh
                  - default.sqs                       # k8s secret: <namespace>.<secretname>
                  - kube-system.ssh-keys
            variables:                                # `-var-file="testing.tfvars"`
              - storage: (kubernetes|file)            # k8s configmap, local files
                paths:
                  - simloud.profile                   # k8s configmap: <namespace>.<configmap>
                  - ./variable.tfvars                 # local file location
                  - keys:
                key1: value
                key2: balue

        # === SHELL: SH, BASH, ZSH ===
        - shell: bash                                # “bash” by default ( optional ). There are sh, zsh values are available
          args: []                                   # shell arguments ( optional )
          homedir: ./                                # shell command default folder ( optional )
          scripts:                                   # for “sh,bash,zsh” shells only
            - echo “hello!”


