version: v1
kind: simloud-pipeline

pipeline:
  default:                                       # profile name. Currently available only 'default'
    - action: deploy,destroy
      state: build,create,update,destroy
      stages:
        - name: “TF code”
          shell: terraform
          args: []
          homedir: ./                                # shell command directory
          terraform:
            version: 0.13                            # tf version, by default 0.12
            workspace: default                       # Workspace’s name. Default workspace: default
            statefile:                               # state file location
              storage: kubernetes                    # by default is “kubernetes”
              location: default.k8s-state            # k8s: <namespace>.<secret_suffix>
            secrets:                                 # `-var-file="testing.tfvars"`
              - storage: kubernetes                  # vault or k8s secrets values are available
                paths:                               # vault paths, or k8s secrets names
                  - kube-system.ssh-keys
